steps:
  - label: "Danger"
    commands:
      - bundle install
      - bundle exec danger --verbose
  - label: "Analyze"
    command: make analyze
  - label: "TSan Unit Tests"
    command: make test_tsan
